library: ~/Music/beets.blb
directory: ~/Music/
plugins: inline
import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: yes
    log: beetslog.txt
    incremental: yes
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: folder.jpg
threaded: yes
color: yes 
per_disc_numbering: yes
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''

asciify_paths:
    default: $albumartist/%if{$year,$year - }$album%aunique{}/%if{$multidisc,$disc}%if{$track,$track - }%if{$artist,$artist - }$title
paths:
    default: $albumartist/%if{$year,$year - }$album%aunique{}/%if{$multidisc,$disc}%if{$track,$track - }%if{$artist,$artist - }$title
item_fields:
    multidisc: 1 if disctotal > 1 else 0

musicbrainz:
    host: musicbrainz.tranquilbase.org:80
    ratelimit: 1
