#!/bin/bash

export STARTBRANCH=`git rev-parse --abbrev-ref HEAD`;
git checkout master;
git svn fetch;
git svn rebase -l;
git rebase master work;
for i in `git br| grep -vP "master|work|RB_" | sed 's/\*/\ /'`; do 
    git rebase work $i; 
done;
#echo
#echo "Updating out-for-review branches."
#for i in `git br| grep -P "^\s*R" | sed 's/\*/\ /'`; do
#    git rebase master $i;
#done;
git tag -f old_work work
echo
git co $STARTBRANCH
echo
echo "Updating external repositories."
git avup
